# Generated by Django 3.0.6 on 2020-10-31 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_user_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9),
        ),
    ]
