# Generated by Django 3.0.6 on 2020-10-31 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201031_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='category',
            field=models.CharField(help_text='write category type of your listing', max_length=50),
        ),
    ]
