# Generated by Django 3.0.6 on 2020-10-31 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20201031_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_listing',
            name='price',
        ),
    ]
