# Generated by Django 3.0.6 on 2020-11-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_auction_listing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
