# Generated by Django 3.0.6 on 2020-11-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20201128_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='URL_image',
            field=models.CharField(blank=True, default='./static/default.png', help_text='Url of image that going to be displayed on your listing', max_length=2000),
        ),
    ]
